name: GitLab Runner Service
description: 'Runs a gitlab runner using the token authentication method'
author: 'Torben Raab'
branding:
  icon: 'server'
  color: 'purple'
inputs:
  job-count:
    description: 'Number of jobs that should be runner'
    required: false
    default: '1'
  gitlab-instance:
    description: 'Gitlab instance'
    required: true
    default: 'https://gitlab.com/'
  token:
    description: 'Token'
    required: true
  name:
    description: 'Runner name'
    required: true
  docker-image:
    description: 'Docker image used by runner'
    required: false
    default: 'docker:25'
  run-untagged:
    description: "Parameter that allows or not to pick untagged jobs"
    required: false
    default: 'true'
  access-level:
    description: 'Parameter to create or not a protected runner'
    required: false
    default: "not_protected"
runs:
  using: 'node20'
  main: 'dist/index.js'